version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: |
            cd qa-engineer-api/apis/contrato
            bundle check || bundle install
      - run:
          name: Dados Inválidos
          command: |
            cd qa-engineer-api/apis/contrato
            env=invalid bundle exec rspec tests/* --order defined -fd \
                                                  --format RspecJunitFormatter \
                                                  --out /home/circleci/project/test_results/rspec.xml \
                                                  --fail-fast
      # - run:
      #     name: Dados Válidos
      #     command: |
      #       cd qa-engineer-api/apis/contrato
      #       bundle exec rspec tests/* --order defined -fd \
      #                                             --format RspecJunitFormatter \
      #                                             --out /home/circleci/project/test_results/rspec.xml
      - store_test_results:
          path: test_results
